### ISSUE TITLE
Finished challenge

### ISSUE THREAD

**Issue by mentix02** [LH-Ventures/Python-Coding-Challenge#1]
Here's the completed repo -[mentix02/Python-Coding-Challenge](https://github.com/mentix02/Python-Coding-Challenge)

**Comment by krishnakarki195** [comment]
[Here is my solution](https://github.com/krishnakarki195/Python-Coding-Challenge.git)

**Comment by SirDukey** [comment]
Finished it, its probably a bit hackey though still works
https://github.com/SirDukey/bucky_challenge
